name: Run Lintter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - server
          - client

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}

      - name: Run lint script
        run: |
          cd ${{ matrix.project }}
          npm run lint:fix
