name: Run Linter and Formatter

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - server
          - client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}
          npm install

      - name: Run Prettier
        run: |
          cd ${{ matrix.project }}
          npm run format

      - name: Run lint script
        run: |
          cd ${{ matrix.project }}
          npm run lint:fix
